export const ADD_INGREDIENT ='ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS= 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED ='FETCH_INGREDIENTS_FAILED';


export const PURCHASE_BURGER_SUCCESS="PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAILED ="PURCHASE_BURGER_FAILED";
export const PURCHASE_BURGER_START="PURCHASE_BURGER_START";

export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_ORDERS_START ="FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS="FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAILED="FETCH_ORDERS_FAILED";

export const AUTH_START ="AUTH_START";
export const AUTH_SUCCESS="AUTH_SUCCESS";
export const AUTH_FAILED="AUTH_FAILED";

export const AUTH_INITIATE_LOGOUT="AUTH_INITIATE_LOGOUT";
export const AUTH_LOGOUT ="AUTH_LOGOUT";

export const AUTH_REDIRECT_PATH = "AUTH_REDIRECT_PATH";

export const AUTH_CHECKOUT_TIMEOUT = "AUTH_CHECKOUT_TIMEOUT";


export const AUTH_USER="AUTH_USER";

export const AUTH_CHECK_STATE="AUTH_CHECK_STATE";